### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ZhangScream** [snap-research/Panda-70M#19]
I run the captioning file.
`python inference.py --video-list inputs/video_list.txt --prompt-list inputs/prompt_list.txt`
and encountered the following issues

`/root/anaconda3/envs/panda70m_captioning/lib/python3.9/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/root/anaconda3/envs/panda70m_captioning/lib/python3.9/site-packages/torchvision/transforms/_transforms_video.py:25: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.02s/it]
Load first Checkpoint: checkpoint/checkpoint_best.pth
Traceback (most recent call last):
  File "/dfs/comicai/bo.lii/Code/panda-70M/captioning/inference.py", line 38, in <module>
    model = model_cls.from_config(model_config).to("cuda")
  File "/dfs/comicai/bo.lii/Code/panda-70M/captioning/video_llama/models/video_llama.py", line 648, in from_config
    ckpt = torch.load(ckpt_path, map_location="cpu")
  File "/root/anaconda3/envs/panda70m_captioning/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/anaconda3/envs/panda70m_captioning/lib/python3.9/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

**Comment by tsaishien-chen** [comment]
Hi @ZhangScream, could you check whether the checkpoint has been downloaded correctly? The file size should be 3.8GB.
If not, please try to download the checkpoint manually.
