### ISSUE TITLE
error when pip install the requirements for video spiltting

### ISSUE THREAD

**Issue by tengjiayan20** [snap-research/Panda-70M#23]
Collecting types-regex (from -r requirements.txt (line 15))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/58/85/9d92b532770d40707da7b4ca92aec1d932fb40d89924135f870dcdd4e592/types_regex-2023.12.25.20240311-py3-none-any.whl (5.3 kB)
Collecting mayavi (from -r requirements.txt (line 16))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bc/1e/cd53cd7ec13768e571252f7ae6ec9c1e12ec04454691e666728234022ed5/mayavi-4.8.1.tar.gz (20.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 78.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      running egg_info
      running build_src
      Building tvtk_classes.zip
      ----------------------------------------------------------------------
      Deleting possibly old TVTK classes
      Building TVTK classes... vtkAnimationCue: Ignoring method: Get/SetDirection
      default: 1, range: None
      vtkContextDevice2D: Ignoring method: Get/SetViewportRect
      default: [-1075490704, 32517, -1075490704, 32517], range: None
      vtkContextDevice2D: Ignoring method: Get/SetViewportSize
      default: [-1075490704, 32517], range: None
      vtkEventDataForDevice: Ignoring method: Get/SetAction
      default: -1, range: None
      vtkEventDataForDevice: Ignoring method: Get/SetDevice
      default: -1, range: None
      vtkFXAAOptions: Ignoring method: Get/SetDebugOptionValue
      default: 0, range: None
      vtkIncrementalForceLayout: Ignoring method: Get/SetGravityPoint
      default: [200.0, 200.0], range: None
      vtkLineIntegralConvolution2D: MaxNoiseValue not updatable (VTK 9.2 bug - value not properly initialized)
      vtkOpenGLBufferObject: Ignoring method: Get/SetType
      default: 0, range: None
      vtkOpenGLFXAAFilter: Ignoring method: Get/SetDebugOptionValue
      default: 0, range: None
      vtkRenderWidget: Ignoring method: Get/SetPosition
      default: [0, 0], range: None
      vtkRenderWidget: Ignoring method: Get/SetSize
      default: [300, 300], range: None
      vtkShader: Ignoring method: Get/SetType
      default: 3, range: None
      vtkViewport: Ignoring method: Get/SetGradientMode
      default: 0, range: None
      vtkVolumeTexture: Ignoring method: Get/SetPartitions
      default: [1, 1, 1], range: None
      vtkChartMatrix: Ignoring method: Get/SetFillStrategy
      default: 0, range: None
      vtkChartMatrix: Ignoring method: Get/SetGutter
      default: [15.0, 15.0], range: None
      vtkChartMatrix: Ignoring method: Get/SetRect
      default: [0, 0, 100, 100], range: None
      vtkChartMatrix: Ignoring method: Get/SetSize
      default: [0, 0], range: None
      vtkContextArea: Ignoring method: Get/SetDrawAreaBounds
      default: [0.0, 0.0, 300.0, 300.0], range: None
      vtkContextArea: Ignoring method: Get/SetDrawAreaResizeBehavior
      default: 0, range: None
      vtkContextArea: Ignoring method: Get/SetFixedMargins
      default: [0, 0, 0, 0], range: None
      vtkContextArea: Ignoring method: Get/SetFixedRect
      default: [0, 0, 300, 300], range: None
      vtkContextArea: Ignoring method: Get/SetGeometry
      default: [0, 0, 300, 300], range: None
      vtkImplicitProjectOnPlaneDistance: Ignoring method: Get/SetNorm
      default: 2, range: None
      
      
      Failed on OpenGLCellGridRenderRequest
      (#5 of 11 nodes, #227 of 464 subnodes):
      Traceback (most recent call last):
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/code_gen.py", line 142, in generate_code
          self._write_wrapper_class(node, tvtk_name)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/code_gen.py", line 235, in _write_wrapper_class
          self.wrap_gen.generate_code(node, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 242, in generate_code
          self._gen_methods(node, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 361, in _gen_methods
          get_set, allow_update_failure = self._gen_get_set_methods(klass, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 774, in _gen_get_set_methods
          self._write_trait_with_range(klass, out, vtk_attr_name)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 1550, in _write_trait_with_range
          if (default > rng[1]) and (default - rng[1]) < 2:
      TypeError: unsupported operand type(s) for -: 'str' and 'str'
      
      
      Traceback (most recent call last):
        File "/share/home/tjy/anaconda3/envs/panda70m/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/share/home/tjy/anaconda3/envs/panda70m/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/share/home/tjy/anaconda3/envs/panda70m/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 432, in <module>
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 171, in setup
          return old_setup(**new_attr)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/numpy/distutils/command/egg_info.py", line 26, in run
          self.run_command("build_src")
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-89dvkl5g/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 299, in run
        File "<string>", line 273, in build_tvtk_classes_zip
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/setup.py", line 98, in gen_tvtk_classes_zip
          gen.generate_code()
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/code_gen.py", line 142, in generate_code
          self._write_wrapper_class(node, tvtk_name)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/code_gen.py", line 235, in _write_wrapper_class
          self.wrap_gen.generate_code(node, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 242, in generate_code
          self._gen_methods(node, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 361, in _gen_methods
          get_set, allow_update_failure = self._gen_get_set_methods(klass, out)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 774, in _gen_get_set_methods
          self._write_trait_with_range(klass, out, vtk_attr_name)
        File "/tmp/pip-install-ulhp1pw9/mayavi_b5eed71ca81948edb4a43f8318a7998a/tvtk/wrapper_gen.py", line 1550, in _write_trait_with_range
          if (default > rng[1]) and (default - rng[1]) < 2:
      TypeError: unsupported operand type(s) for -: 'str' and 'str'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tengjiayan20** [comment]
![image](https://github.com/snap-research/Panda-70M/assets/97726897/3b8afebc-3632-496a-83e9-3fbda4c4b821)
And it seems that corresponding lines are here?

**Comment by tsaishien-chen** [comment]
You are right and the problems has been solved. Thanks for letting know!
